{"text": "2023-12-24 12:44:40 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}\n", "record": {"elapsed": {"repr": "0:00:01.927539", "seconds": 1.927539}, "exception": null, "extra": {"image": "20231121", "version": "0.10.1.post2", "role": "EpicPlayer", "headless": true}, "file": {"name": "claim.py", "path": "/home/runner/work/egames4/egames4/epic/src/claim.py"}, "function": "stash", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 131, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 5216, "name": "MainProcess"}, "thread": {"id": 140171199085440, "name": "MainThread"}, "time": {"repr": "2023-12-24 12:44:40.920003+08:00", "timestamp": 1703393080.920003}}}
{"text": "2023-12-24 12:44:48 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Fallout 3: Game of the Year Edition', 'url': 'https://store.epicgames.com/en-US/p/fallout-3-game-of-the-year-edition'}\n", "record": {"elapsed": {"repr": "0:00:09.624712", "seconds": 9.624712}, "exception": null, "extra": {"title": "Fallout 3: Game of the Year Edition", "url": "https://store.epicgames.com/en-US/p/fallout-3-game-of-the-year-edition"}, "file": {"name": "claim.py", "path": "/home/runner/work/egames4/egames4/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 66, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 5216, "name": "MainProcess"}, "thread": {"id": 140171199085440, "name": "MainThread"}, "time": {"repr": "2023-12-24 12:44:48.617176+08:00", "timestamp": 1703393088.617176}}}
{"text": "2023-12-24 12:44:48 | ERROR    | hcaptcha_challenger.onnx.modelhub:flush_runtime_assets:190 | 0 - {}\n", "record": {"elapsed": {"repr": "0:00:09.868959", "seconds": 9.868959}, "exception": null, "extra": {}, "file": {"name": "modelhub.py", "path": "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/onnx/modelhub.py"}, "function": "flush_runtime_assets", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 190, "message": "0", "module": "modelhub", "name": "hcaptcha_challenger.onnx.modelhub", "process": {"id": 5216, "name": "MainProcess"}, "thread": {"id": 140171199085440, "name": "MainThread"}, "time": {"repr": "2023-12-24 12:44:48.861423+08:00", "timestamp": 1703393088.861423}}}
{"text": "2023-12-24 12:44:49 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/fallout-3-game-of-the-year-edition'}\n", "record": {"elapsed": {"repr": "0:00:10.068381", "seconds": 10.068381}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/fallout-3-game-of-the-year-edition"}, "file": {"name": "agent.py", "path": "/home/runner/work/egames4/egames4/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 5216, "name": "MainProcess"}, "thread": {"id": 140171199085440, "name": "MainThread"}, "time": {"repr": "2023-12-24 12:44:49.060845+08:00", "timestamp": 1703393089.060845}}}
{"text": "2023-12-24 12:44:56 | INFO    | epic_games.agent:claim_weekly_games:326 | claim_weekly_games - {'action': 'move to webPurchaseContainer iframe'}\n", "record": {"elapsed": {"repr": "0:00:17.517853", "seconds": 17.517853}, "exception": null, "extra": {"action": "move to webPurchaseContainer iframe"}, "file": {"name": "agent.py", "path": "/home/runner/work/egames4/egames4/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 326, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 5216, "name": "MainProcess"}, "thread": {"id": 140171199085440, "name": "MainThread"}, "time": {"repr": "2023-12-24 12:44:56.510317+08:00", "timestamp": 1703393096.510317}}}
{"text": "2023-12-24 12:44:58 | INFO    | epic_games.agent:claim_weekly_games:328 | claim_weekly_games - {'action': 'click payment button'}\n", "record": {"elapsed": {"repr": "0:00:20.000062", "seconds": 20.000062}, "exception": null, "extra": {"action": "click payment button"}, "file": {"name": "agent.py", "path": "/home/runner/work/egames4/egames4/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 328, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 5216, "name": "MainProcess"}, "thread": {"id": 140171199085440, "name": "MainThread"}, "time": {"repr": "2023-12-24 12:44:58.992526+08:00", "timestamp": 1703393098.992526}}}
{"text": "2023-12-24 12:45:03 | DEBUG    | hcaptcha_challenger.agents.playwright.control:_parse_label:241 | get task - {'prompt': 'Ple–∞se click e–∞c“ª image containing an object used in garden'}\n", "record": {"elapsed": {"repr": "0:00:25.002744", "seconds": 25.002744}, "exception": null, "extra": {"prompt": "Ple–∞se click e–∞c“ª image containing an object used in garden"}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "_parse_label", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 241, "message": "get task", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 5216, "name": "MainProcess"}, "thread": {"id": 140171199085440, "name": "MainThread"}, "time": {"repr": "2023-12-24 12:45:03.995208+08:00", "timestamp": 1703393103.995208}}}
{"text": "2023-12-24 12:45:04 | DEBUG    | hcaptcha_challenger.agents.playwright.control:_catch_all_binary_challenge:474 | handle task - {'unsupervised': 'binary', 'candidate_labels': ['This is a picture that looks like object used in garden.', \"This is a picture that don't look like object used in garden.\"], 'prompt': 'Ple–∞se click e–∞c“ª image containing an object used in garden', 'timit': '0.132s'}\n", "record": {"elapsed": {"repr": "0:00:25.250528", "seconds": 25.250528}, "exception": null, "extra": {"unsupervised": "binary", "candidate_labels": ["This is a picture that looks like object used in garden.", "This is a picture that don't look like object used in garden."], "prompt": "Ple–∞se click e–∞c“ª image containing an object used in garden", "timit": "0.132s"}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "_catch_all_binary_challenge", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 474, "message": "handle task", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 5216, "name": "MainProcess"}, "thread": {"id": 140171199085440, "name": "MainThread"}, "time": {"repr": "2023-12-24 12:45:04.242992+08:00", "timestamp": 1703393104.242992}}}
{"text": "2023-12-24 12:45:04 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (5216), thread 'MainThread' (140171199085440): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 158, in run\n    await agent.stash()\n  File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 151, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 122, in claim_epic_games\n    await epic.claim_weekly_games(page, single_promotions)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 88, in async_wrapped\n    return await fn(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 47, in __call__\n    do = self.iter(retry_state=retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 314, in iter\n    return fut.result()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 50, in __call__\n    result = await fn(*args, **kwargs)\n  File \"/home/runner/work/egames4/egames4/epic/src/epic_games/agent.py\", line 335, in claim_weekly_games\n    await self.handle.insert_challenge(self._solver, page, wpc, payment_btn, recur_url, is_uk)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 88, in async_wrapped\n    return await fn(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 47, in __call__\n    do = self.iter(retry_state=retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 314, in iter\n    return fut.result()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 50, in __call__\n    result = await fn(*args, **kwargs)\n  File \"/home/runner/work/egames4/egames4/epic/src/epic_games/agent.py\", line 105, in insert_challenge\n    response = await solver.execute(window=\"free\")\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py\", line 642, in execute\n    await self._catch_all_binary_challenge(frame_challenge)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py\", line 486, in _catch_all_binary_challenge\n    results = tool(model, image=Image.open(example_path))\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/components/zero_shot_image_classifier.py\", line 139, in __call__\n    predictions = detector(image, candidate_labels=self.candidate_labels)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/onnx/clip.py\", line 411, in __call__\n    image_features = self.encode_image(images)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/onnx/clip.py\", line 375, in encode_image\n    input_name = self.visual_session.get_inputs()[0].name\nAttributeError: 'NoneType' object has no attribute 'get_inputs'\n", "record": {"elapsed": {"repr": "0:00:25.537378", "seconds": 25.537378}, "exception": {"type": "AttributeError", "value": "'NoneType' object has no attribute 'get_inputs'", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/egames4/egames4/epic/src/claim.py"}, "function": "run", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 158, "message": "An error has been caught in function 'run', process 'MainProcess' (5216), thread 'MainThread' (140171199085440):", "module": "claim", "name": "__main__", "process": {"id": 5216, "name": "MainProcess"}, "thread": {"id": 140171199085440, "name": "MainThread"}, "time": {"repr": "2023-12-24 12:45:04.529842+08:00", "timestamp": 1703393104.529842}}}
