{"text": "2023-10-07 12:42:44 | INFO    | __main__:from_epic:40 | run - {'stage': 'Initialization EpicPlayer'}\n", "record": {"elapsed": {"repr": "0:00:00.979666", "seconds": 0.979666}, "exception": null, "extra": {"stage": "Initialization EpicPlayer"}, "file": {"name": "claim.py", "path": "/home/runner/work/egames4/egames4/epic/src/claim.py"}, "function": "from_epic", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 40, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 3785, "name": "MainProcess"}, "thread": {"id": 140509661936512, "name": "MainThread"}, "time": {"repr": "2023-10-07 12:42:44.659755+08:00", "timestamp": 1696653764.659755}}}
{"text": "2023-10-07 12:42:49 | INFO    | __main__:claim_epic_games:86 | Try to flush cookie - {'task': 'claim_epic_games'}\n", "record": {"elapsed": {"repr": "0:00:05.939790", "seconds": 5.93979}, "exception": null, "extra": {"task": "claim_epic_games"}, "file": {"name": "claim.py", "path": "/home/runner/work/egames4/egames4/epic/src/claim.py"}, "function": "claim_epic_games", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 86, "message": "Try to flush cookie", "module": "claim", "name": "__main__", "process": {"id": 3785, "name": "MainProcess"}, "thread": {"id": 140509661936512, "name": "MainThread"}, "time": {"repr": "2023-10-07 12:42:49.619879+08:00", "timestamp": 1696653769.619879}}}
{"text": "2023-10-07 12:42:49 | ERROR    | __main__:run:126 | An error has been caught in function 'run', process 'MainProcess' (3785), thread 'MainThread' (140509661936512): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 130, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 126, in run\n    await agent.stash()\n  File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 120, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 87, in claim_epic_games\n    if await epic.authorize(page):\n  File \"/home/runner/work/egames4/egames4/epic/src/services/agents/epic_games.py\", line 134, in authorize\n    match await self._login(page):\n  File \"/home/runner/work/egames4/egames4/epic/src/services/agents/epic_games.py\", line 91, in _login\n    await page.goto(URL_CLAIM, wait_until=\"domcontentloaded\")\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 9251, in goto\n    await self._impl_obj.goto(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_page.py\", line 473, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py\", line 138, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 482, in wrap_api_call\n    return await cb()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 97, in inner_send\n    result = next(iter(done)).result()\nplaywright._impl._api_types.Error: NS_BINDING_ABORTED\n=========================== logs ===========================\nnavigating to \"https://store.epicgames.com/en-US/free-games\", waiting until \"domcontentloaded\"\n============================================================\n", "record": {"elapsed": {"repr": "0:00:06.241048", "seconds": 6.241048}, "exception": {"type": "Error", "value": "NS_BINDING_ABORTED\n=========================== logs ===========================\nnavigating to \"https://store.epicgames.com/en-US/free-games\", waiting until \"domcontentloaded\"\n============================================================", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/egames4/egames4/epic/src/claim.py"}, "function": "run", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 126, "message": "An error has been caught in function 'run', process 'MainProcess' (3785), thread 'MainThread' (140509661936512):", "module": "claim", "name": "__main__", "process": {"id": 3785, "name": "MainProcess"}, "thread": {"id": 140509661936512, "name": "MainThread"}, "time": {"repr": "2023-10-07 12:42:49.921137+08:00", "timestamp": 1696653769.921137}}}
